### PR TITLE
Adds the Marionette Inspector

### PR DESCRIPTION
**Pull request by jasonLaster**
Hello! 

I hope I did this correctly, I wasn't exactly sure how to get the local docs to look the same.

### CODE REVIEW

**Comment by Garbee** [comment]
lgtm.

And the local version doesn't ever look exactly the same. Certain JS doesn't run among other things. It is close enough to be functional though.

**Comment by jasonLaster** [comment]
Haha, good to know.

Couple of follow up questions:
+ I couldn't find a link to the extension-gallery. Is there one? Should there be one?
+ Is sample extensions still in use? 
+ I think this page could use a table of contents because it's a long list, any interest in one?

**Comment by Garbee** [comment]
Doing a quick search of the repo there isn't an internal link. As far as having one, along with a ToC, not a big deal. We are beginning a move of a good chunk of the current content into another place. We will assess the gallery and see how to improve it (and link it up) in the move.

Sample extensions... same boat as the gallery imo. Some of the same content, but much less. We should merge these in our content move. Thanks for bringing it up!

**Comment by jasonLaster** [comment]
no problem. glad to hear that docs are getting some love

**Pull request merged**
