### PR TITLE
Add color picker docs.

### LINKED ISSUE #236: Eyedropper
The eyedropper for color selection is out (or close.) We should get this functionality added to the docs.

### PR DESCRIPTION
**Pull request by samccone**
Fixes #236

### CODE REVIEW

**Comment by samccone** [comment]
:palm_tree:

**Comment by Garbee** [comment]
The only possible issue here is the image. We prefer to use Google-properties (now primarily the doc page itself if possible) for instructional aids.

Could you take the time to do another gif using the dom-and-styles doc page please?

**Comment by samccone** [comment]
Sure sure. Palm trees are so 2014 anyway

**Comment by samccone** [comment]
kk @Garbee :goat:

**Comment by Garbee** [comment]
Very nice. Thanks!

**Pull request merged**
