### PR TITLE
Fix demos/memory/example7.html not working

### PR DESCRIPTION
**Pull request by jakub-g**
The example did not have real JS code loaded. I copy-pasted the snippet into a `<script>` tag, the same way it's done in the other files.

Also removed duplicated `</script>` tags in other files

### CODE REVIEW

**Comment by jakub-g** [comment]
just noticed that example 7 is just a broken version of example 8, probably it should be removed at all :)

**Comment by Garbee** [comment]
We are working on moving most of this stuff around soon anyways. So examples will be cleaned up once other things are addressed. For now just cleaning up the code to them is fantastic in case it gets re-used in the new structure.

I think GoogleBot is drunk... Afaik we don't have CLA restrictions on this repo. However, I will wait for conformation in case this has changed recently.

Thanks so much for the PR!

**Comment by Garbee** [comment]
So, just got word. We do require a CLA be signed for the documentation. So, Googlebot is not drunk, we were just mistaken. :frowning: 

If you could just follow what GoogleBot instructs for signing the CLA and get back to us that would be fantastic.

**Comment by paulirish** [comment]
@Garbee I was under belief that CLAs were unnecessary for documentation changes, but I have learned this is incorrect. We'll need a CLA signed for all PRs, even if its a typo change. Kind of annoying but... lawyers and stuff. 

Oh you just beat me to it.

**Comment by Garbee** [comment]
I'm quick! :wink:

**Comment by paulirish** [comment]
so fastttttt :speedboat:

**Comment by Garbee** [comment]
Much wow! :wolf:

**Pull request merged**
