### PR TITLE
Made appropriate tables into definition lists.

### PR DESCRIPTION
**Pull request by Garbee**
Simply re-factored tables into Definition Lists where appropriate. Also cleaned up an old mistake of mine where I defined the same abbreviations repeatedly in the network timing reference list.

### CODE REVIEW

**Comment by paulirish** [comment]
I believe the formatting may have been deliberate here. Side-by-side is very nice for this stuff.

going DL do we lose that?

**Comment by Garbee** [comment]
eh, it goes to DT just above and to the left of DD by default.

However, if you want side-by-side, I actually agree with that and we can just restyle <dl>'s. I was planning on submitting a requests in a day or two for some style additions once I've played around some more. I can add this onto that if you want.

If we style them side-by-side, then we get the more semantic markup and the design.

**Comment by paulirish** [comment]
cool. i have a hard time reading the alternating dt/dd vs side-by-side.

i'm fine with updating semantics and then matching style.

**Comment by paulirish** [comment]
some open comments for this over in #250 which i just closed to simplify things.

**Comment by Garbee** [comment]
I was doing the colon after dt to just save us some typing... however. In doing the console page it can actually make things confusing in some cases. So it will be nuked.

I only need to figure out how to handle a definition with two terms. Currently there is one thing I think in here and in the console PR that is problematic with the `.one-to-one` styling I had in the other PR. I may just go to not doing multiple `<dt>` and just do one with *or* between the terms (ugh.) Not good, but that is 95% of the way to using the best applicable markup.

**Comment by Garbee** [comment]
```css
dt {
    font-weight: bold;
    float: left;
    width: 160px;
    clear: left;
   
}

dt.full-width {
  width: 100%;
}

dl:before,
dl:after {
    display: table;
    content: " ";
}

dl:after {
    clear:both;
}

dd {
    margin: 0 0 15px 180px;
}

@media(max-width:580px) {
    dt {
        width: 100%;
    }
    dd {
        width: 100%;
        margin-left: 0;
    }
}
```

This will give us the nice ordered style. If a definition has multiple terms, we give the upper terms a `full-width` class. That will set the width to 100%  so related terms stack. Here are example views:

Network connection points on mobile:
network_connection_points_mobile

Network connection points desktop/tablet:
network_connection_points_desktop

Console formatters (One definition multiple terms) desktop:
console_formatters_desktop

Console formatters (One definition multiple terms) mobile:
console_formatters_mobile

On phones the `dl` stacks. Good margin on the bottom as well so this are more clearly related in view.

Anything wrong here?

**Comment by paulirish** [comment]
this LGTM

**Comment by paulirish** [comment]
CL up for review: https://codereview.chromium.org/992023002

`dl.nice`

**Comment by Garbee** [comment]
Egotistical class name: `dl.garbee`

haha

**Comment by Garbee** [comment]
Updated this doc with the class. Did realize I have a nested `<dl>` here... Need to keep an eye on that and will fix it if the styling is horrible (which I am assuming is probably what will happen.)

**Comment by Garbee** [comment]
Styling is merged upstream and in production. Merging the PR since that is completed.

**Comment by paulirish** [comment]
done

image

**Pull request merged**
