### PR TITLE
Small javascript-debugging fixes

### PR DESCRIPTION
**Pull request by evverx**
* Fixed broken link to Google Closure hovercard demo
* Fixed unreadable note (added newline for readability)
* Fixed pause/resume shortcuts ( / -> \ )
* Fixed broken link to Angular version of TodoMVC
* Fixed "Pause on [Uncaught]? Exceptions" sections

### CODE REVIEW

**Comment by evverx** [comment]
I signed it!

**Comment by evverx** [comment]
screen shot 2015-05-21 at 10 40 22

**Comment by Garbee** [comment]
@paulirish Do we want to keep pulling in commits to this content since it is about to be moved out soon?

**Comment by evverx** [comment]
Hm, looks like the [new documentation](https://web-central.appspot.com/web/tools/javascript/exceptions-errors/track-exceptions?hl=en) is out of date too:)

**Comment by Garbee** [comment]
Yea, new docs are rolling out and these will eventually redirect over to that. I'm thinking any content for things being moved should be updated in the Web Fundamentals repo now instead of here.

**Comment by evverx** [comment]
@Garbee , ok. Thanks.

**Comment by paulirish** [comment]
yah i'd rather at least accept these small PRs while we focus primary
efforts on WF.
merging them wont be too hard.​

**Comment by Garbee** [comment]
Merged on in then. Thanks for the PR @evverx.

**Pull request merged**
